"""baseline: all existing tables

Revision ID: dfe8be4881a7
Revises: 
Create Date: 2026-03-14 18:08:17.384160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfe8be4881a7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_uuid', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('parsed_data', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_cache_run_uuid'), 'analysis_cache', ['run_uuid'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_conversation_id'), 'conversation_messages', ['conversation_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_project_id'), 'conversations', ['project_id'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('deleted_project_token_daily',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('usage_date', sa.String(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('assistant_message_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deleted_project_token_daily_project_id'), 'deleted_project_token_daily', ['project_id'], unique=False)
    op.create_index(op.f('ix_deleted_project_token_daily_usage_date'), 'deleted_project_token_daily', ['usage_date'], unique=False)
    op.create_index(op.f('ix_deleted_project_token_daily_user_id'), 'deleted_project_token_daily', ['user_id'], unique=False)
    op.create_table('deleted_project_token_usage',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('conversation_count', sa.Integer(), nullable=False),
    sa.Column('assistant_message_count', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deleted_project_token_usage_project_id'), 'deleted_project_token_usage', ['project_id'], unique=True)
    op.create_index(op.f('ix_deleted_project_token_usage_user_id'), 'deleted_project_token_usage', ['user_id'], unique=False)
    op.create_table('dogme_jobs',
    sa.Column('run_uuid', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('sample_name', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('input_directory', sa.String(), nullable=False),
    sa.Column('reference_genome', sa.String(), nullable=True),
    sa.Column('modifications', sa.String(), nullable=True),
    sa.Column('nextflow_work_dir', sa.String(), nullable=True),
    sa.Column('nextflow_config_path', sa.String(), nullable=True),
    sa.Column('nextflow_process_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('output_directory', sa.String(), nullable=True),
    sa.Column('report_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('log_file', sa.String(), nullable=True),
    sa.Column('stderr_log', sa.String(), nullable=True),
    sa.Column('parent_block_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('run_uuid')
    )
    op.create_index(op.f('ix_dogme_jobs_project_id'), 'dogme_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_dogme_jobs_status'), 'dogme_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_dogme_jobs_user_id'), 'dogme_jobs', ['user_id'], unique=False)
    op.create_table('job_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_uuid', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_logs_run_uuid'), 'job_logs', ['run_uuid'], unique=False)
    op.create_table('job_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('run_uuid', sa.String(), nullable=False),
    sa.Column('sample_name', sa.String(), nullable=False),
    sa.Column('workflow_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_results_conversation_id'), 'job_results', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_job_results_run_uuid'), 'job_results', ['run_uuid'], unique=False)
    op.create_table('project_access',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('last_accessed', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_access_project_id'), 'project_access', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_access_user_id'), 'project_access', ['user_id'], unique=False)
    op.create_table('project_blocks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_blocks_owner_id'), 'project_blocks', ['owner_id'], unique=False)
    op.create_index(op.f('ix_project_blocks_project_id'), 'project_blocks', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_blocks_seq'), 'project_blocks', ['seq'], unique=False)
    op.create_table('project_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('source_key', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('parent_task_id', sa.String(), nullable=True),
    sa.Column('action_label', sa.String(), nullable=True),
    sa.Column('action_target', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_tasks_kind'), 'project_tasks', ['kind'], unique=False)
    op.create_index(op.f('ix_project_tasks_owner_id'), 'project_tasks', ['owner_id'], unique=False)
    op.create_index(op.f('ix_project_tasks_project_id'), 'project_tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_tasks_source_key'), 'project_tasks', ['source_key'], unique=False)
    op.create_index(op.f('ix_project_tasks_status'), 'project_tasks', ['status'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_file_project_links',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_file_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('symlink_path', sa.Text(), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_file_project_links_project_id'), 'user_file_project_links', ['project_id'], unique=False)
    op.create_index(op.f('ix_user_file_project_links_user_file_id'), 'user_file_project_links', ['user_file_id'], unique=False)
    op.create_table('user_files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('md5_hash', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('encode_accession', sa.String(), nullable=True),
    sa.Column('sample_name', sa.String(), nullable=True),
    sa.Column('organism', sa.String(), nullable=True),
    sa.Column('tissue', sa.String(), nullable=True),
    sa.Column('tags_json', sa.Text(), nullable=True),
    sa.Column('disk_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_files_user_id'), 'user_files', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('google_sub_id', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_project_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_limit', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_sub_id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index(op.f('ix_user_files_user_id'), table_name='user_files')
    op.drop_table('user_files')
    op.drop_index(op.f('ix_user_file_project_links_user_file_id'), table_name='user_file_project_links')
    op.drop_index(op.f('ix_user_file_project_links_project_id'), table_name='user_file_project_links')
    op.drop_table('user_file_project_links')
    op.drop_table('sessions')
    op.drop_table('projects')
    op.drop_index(op.f('ix_project_tasks_status'), table_name='project_tasks')
    op.drop_index(op.f('ix_project_tasks_source_key'), table_name='project_tasks')
    op.drop_index(op.f('ix_project_tasks_project_id'), table_name='project_tasks')
    op.drop_index(op.f('ix_project_tasks_owner_id'), table_name='project_tasks')
    op.drop_index(op.f('ix_project_tasks_kind'), table_name='project_tasks')
    op.drop_table('project_tasks')
    op.drop_index(op.f('ix_project_blocks_seq'), table_name='project_blocks')
    op.drop_index(op.f('ix_project_blocks_project_id'), table_name='project_blocks')
    op.drop_index(op.f('ix_project_blocks_owner_id'), table_name='project_blocks')
    op.drop_table('project_blocks')
    op.drop_index(op.f('ix_project_access_user_id'), table_name='project_access')
    op.drop_index(op.f('ix_project_access_project_id'), table_name='project_access')
    op.drop_table('project_access')
    op.drop_index(op.f('ix_job_results_run_uuid'), table_name='job_results')
    op.drop_index(op.f('ix_job_results_conversation_id'), table_name='job_results')
    op.drop_table('job_results')
    op.drop_index(op.f('ix_job_logs_run_uuid'), table_name='job_logs')
    op.drop_table('job_logs')
    op.drop_index(op.f('ix_dogme_jobs_user_id'), table_name='dogme_jobs')
    op.drop_index(op.f('ix_dogme_jobs_status'), table_name='dogme_jobs')
    op.drop_index(op.f('ix_dogme_jobs_project_id'), table_name='dogme_jobs')
    op.drop_table('dogme_jobs')
    op.drop_index(op.f('ix_deleted_project_token_usage_user_id'), table_name='deleted_project_token_usage')
    op.drop_index(op.f('ix_deleted_project_token_usage_project_id'), table_name='deleted_project_token_usage')
    op.drop_table('deleted_project_token_usage')
    op.drop_index(op.f('ix_deleted_project_token_daily_user_id'), table_name='deleted_project_token_daily')
    op.drop_index(op.f('ix_deleted_project_token_daily_usage_date'), table_name='deleted_project_token_daily')
    op.drop_index(op.f('ix_deleted_project_token_daily_project_id'), table_name='deleted_project_token_daily')
    op.drop_table('deleted_project_token_daily')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_project_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_conversation_messages_conversation_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_analysis_cache_run_uuid'), table_name='analysis_cache')
    op.drop_table('analysis_cache')
    # ### end Alembic commands ###
