import requests
import json
import time

# --- CONFIG ---
API_URL = "http://localhost:8000"
PROJECT_ID = "test_project_001"
MODEL_KEY = "default"  # Use "fast" or "default"
SKILL = "ENCODE_LongRead"

def run_test():
    print(f"🚀 Starting Chat Test for Project: {PROJECT_ID}")
    print(f"🧠 Model: {MODEL_KEY} | Skill: {SKILL}")
    
    # 1. Define the User Message
    payload = {
        "project_id": PROJECT_ID,
        "message": "Please align the liver tissue sample using the latest reference genome.",
        "skill": SKILL,
        "model": MODEL_KEY
    }

    # 2. Send Request to Server
    print("\n📨 Sending message to Agent (this might take 5-10s)...")
    try:
        start_time = time.time()
        response = requests.post(f"{API_URL}/chat", json=payload)
        duration = time.time() - start_time
        
        response.raise_for_status()
        data = response.json()
        
        print(f"✅ Success! (Took {duration:.2f}s)")
        
    except requests.exceptions.ConnectionError:
        print("❌ Error: Could not connect to server. Is 'uvicorn server1.app:app' running?")
        return
    except Exception as e:
        print(f"❌ Error: {e}")
        print(response.text)
        return

    # 3. Analyze Response
    user_block = data.get("user_block", {})
    agent_block = data.get("agent_block", {})
    
    print("\n--- 🧑 User Block (Stored in DB) ---")
    print(f"ID: {user_block.get('id')}")
    print(f"Text: {user_block.get('payload', {}).get('text')}")

    print("\n--- 🤖 Agent Plan (Generated by LLM) ---")
    print(f"ID: {agent_block.get('id')}")
    print(f"Status: {agent_block.get('status')}")
    
    # Print the actual markdown plan
    plan_content = agent_block.get('payload', {}).get('markdown', '')
    print("\n" + "="*40)
    print(plan_content)
    print("="*40 + "\n")

if __name__ == "__main__":
    run_test()